services:
  app:
    build: .
    dockerfile: Dockerfile
  image: ${APP_IMAGE}
  container_name: ${APP_SERVICE_NAME}
  working_dir: ${APP_WORKDIR}
  volumes:
    - ./laravel/:${APP_WORKDIR}
  ports:
    - "${APP_PORT}:9000"
  depends_on:
    - mysql
  
  nginx:
    image: nginx:latest
    container_name: ${NGINX_SERVICE_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./laravel/:${APP_WORKDIR}
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
  
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_SERVICE_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
    db_data: